### ISSUE TITLE
libcurl 64 bit osx

### ISSUE THREAD

**Issue by borg** [DHaylock/ofxInstagram#1]
Hey,
with the new 0.9 64 version out the door, might be worth addressing libcurl 64 bit. I only spent a moment on this but it seems it ships with OSX and all you need to do is to remove the libs and include the Xcode linked framework "libcurl.tbd".

Might be worth testing a bit and if successful include a note in the read me to save people time.

Thx

**Comment by DHaylock** [comment]
Hi @borg 

Will investigate this today :+1: 

David

**Comment by adielfernandez** [comment]
Hello!

Thanks for putting together this addon. I'm trying to get it to compile and seem to be having trouble with libcurl too. I added libcurl.a to the Link Binary with Libraries section in Build Phases but I still get the error

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lcurl

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lcurl is not an object file (not allowed in a library)
```

I'm assuming it's the same issue raised by @borg since I'm running and OSX 10.11 (Xcode 7.2). Any suggestions?

**Comment by DHaylock** [comment]
Hi @adielfernandez, 

Check out the latest commit. 

Should resolve alot of issues.

When you add the addon it shouldn't include the libs folder which is causing the issues.

Will update the readme later

Best

**Comment by DHaylock** [comment]
Hi @borg 

I've updated the Addon for osx 64.

Any issues let me know

Best
